### ISSUE TITLE
Example doesn't work on Xcode 8, Swift 3.0 now.

### ISSUE THREAD

**Issue by allenlinli** [DroidsOnRoids/RxSwiftExamples#2]
I tried to run ColourfulBall project, but I had to update podfile.
But RxSwift contains Swift 2 even though I used updated podfile as follow.

```
platform :ios, '8.0'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end


target 'ColourfulBall' do
    pod 'RxSwift',    '~> 3.0.0-beta.1'
    pod 'RxCocoa',    '~> 3.0.0-beta.1'
    pod 'RxDataSources', '~> 1.0.0-beta.2'
    pod 'ChameleonFramework/Swift'
end
```

RxSwift in the podfile works fine on other projects.
What's the reason that causes this problem?

And here is the message after I install pod.

```
$ pod install
Analyzing dependencies
Downloading dependencies
Using ChameleonFramework (2.1.0)
Using RxCocoa (3.0.0-beta.2)
Using RxDataSources (1.0.0-beta.3)
Using RxSwift (3.0.0-beta.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 4 total
pods installed.
```

**Comment by allenlinli** [comment]
Found that it's ChameleonFramework that doesn't support Swift 3.0.

**Comment by allenlinli** [comment]
Just found out in RxSwiftExample project, the same problem happened.
It needs me to update RxSwift to Swift 3.0.

```
platform :ios, '10.0'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.10'
    end
  end
end


target 'RxSwiftExample' do
  use_frameworks!

pod 'RxSwift',    '~> 3.0.0-beta.1'
pod 'RxCocoa',    '~> 3.0.0-beta.1'
pod 'RxDataSources', '~> 1.0.0-beta.2'

end
```

**Comment by sunshinejr** [comment]
Hey @allenlinli. Yeah, Examples need update for Swift 3 & RxSwift 3. I'm not sure as of when will I find time for it 😢 but if you, or anyone else, have some spare time for update I will be more than happy to review it.

**Comment by allenlinli** [comment]
Yes, I will try to fix it as I learning :)
A PR has been sent.

**Comment by allenlinli** [comment]
I try to upgrade the project "ColourfulBall" to Swift3.0, but I couldn't do it.
I used podfile mentioned up there, and download the pods:

```
Installing RxCocoa (3.0.0-rc.1)
Installing RxDataSources (1.0.0-rc.2)
Installing RxSwift (3.0.0-rc.1)
```

But failed.

Need someone to help me : (

**Comment by sunshinejr** [comment]
@allenlinli what exactly is the problem? Can you post the error here?

**Comment by allenlinli** [comment]
Xcode said the RxSwift and RxCocoa pods need to be updated to Swift3.0. 
I created a new project with the same podfile, it works fine without any Swift syntax updating needed. It's weird...

**Comment by sunshinejr** [comment]
I think we can now close this one, almost all examples are now updated to 3.0, only one (with MKMapView) isn't, because the lib is not updated yet.
